#!/usr/bin/env ruby
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'shutup'

puts "Killing the process."

Shutup::Rails.hit! && Shutup::Rails.delete_pid
